default_platform(:android)

platform :android do
  desc "Build and test Android app"
  lane :test do
    # Add your test commands here
    gradle(task: "test")
  end

  desc "Build and deploy Android app to Play Store Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(track: 'beta')
  end

  desc "Build and deploy Android app to Play Store"
  lane :release do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

